Initial commit

diff --git a/kern/Makefile b/kern/Makefile
--- a/kern/Makefile
+++ b/kern/Makefile
@@ -2,6 +2,9 @@
 # Adapted from the Dune Kernel Module
 # Adapted from the ipw2200 project.
 
+# We have limited control over the build process of merge files - the kernel
+# decides what compiler, how to do dependency tracking, etc.
+
 ifndef CONFIG_SIVFS
 EXTERNAL_BUILD=y
 CONFIG_SIVFS=m
@@ -13,15 +16,27 @@ list-m :=
 list-$(CONFIG_SIVFS) += sivfs
 obj-$(CONFIG_SIVFS) += sivfs.o
 sivfs-objs := \
-        inode.o \
-        file-mmu.o \
+        sivfs_background_threads.o \
 	sivfs_shared_state.o \
+	sivfs_checkpoints.o \
+        module.o \
+        super.o \
+        inode.o \
 	sivfs_state.o \
+        sivfs_commit_update_checkpoints.o \
+        sivfs_inode_info.o \
+        sivfs_make_checkpoint.o \
+        sivfs_gc_checkpoints.o \
+        sivfs_gc_log.o \
+        sivfs_workingset.o \
+        sivfs_stats.o \
+        sivfs_mm.o \
+        sivfs_nontxnal_ops.o \
+	alloc/sivfs_allocation.o \
 
 # KSRC should be set to the path to your sources
 # modules are installed into KMISC
 KVER  := $(shell uname -r)
-#EXTRACT := $(M)/extract_symbol.sh
 KSRC := /lib/modules/$(KVER)/build
 KMISC := /lib/modules/$(KVER)/kernel/drivers/misc
 KMISC_INC := /lib/modules/$(KVER)/include
@@ -29,18 +44,34 @@ KMISC_INC := /lib/modules/$(KVER)/include
 #SYSCALL_TBL = 0x$(shell $(EXTRACT) sys_call_table)
 #DO_FORK = 0x$(shell $(EXTRACT) do_fork)
 
-ccflags-y :=
+#Set to empty to print out whole commands for added targets
+V := @
 
-ccflags-y += -DDEBUG
+ccflags-y :=
 
 ccflags-y += -Wno-unused
 ccflags-y += -Wno-declaration-after-statement
+ccflags-y += -Wundef
 
 ccflags-y += -O3
+#ccflags-y += -O0
 
+#Comment this to hide all douts
+ccflags-y += -DDEBUG
+#ggdb is a bit fancier than g, but not much
+#ccflags-y += -ggdb
 ccflags-y += -g
+#?
+#ccflags-y += -fno-omit-frame-pointer
 
-#ccflags-y += -ferror-limit=2
+#Static verification using smatch
+ifdef SMATCH
+ifdef RUN_SMATCH
+CHECK := $(SMATCH) --project=kernel --full_path
+CC := $(SMATCHCC)
+CONFIG_DYNAMIC_DEBUG := n
+endif
+endif
 
 # KSRC_OUTPUT should be overridden if you are using a 2.6 kernel that
 # has it's output sent elsewhere via KBUILD_OUTPUT= or O=
@@ -63,10 +94,19 @@ MODPATH := $(DESTDIR)/lib/modules/$(KERNELRELEASE)
 
 all: modules
 
+lint: clean
+	$(V) $(CPPLINT) \
+        --extensions=c,h \
+        *.c *.h \
+	|& grep -v "Done processing" \
+	|& grep -v "Total errors found" \
+        || true
+
 clean:
 	rm -f *.mod.c *.mod *.o *.ko .*.cmd .*.flags .lst *.lst *.order *.symvers
 	rm -f .*.d *.d
 	rm -rf $(PWD)/tmp
+	rm -rf $(PWD)/doc
 #	for file in *.{c,h}; do \
 #		sed -i -e "s:\ *$$::g" -e "s:\t*$$::g" $$file; \
 	done
@@ -76,6 +116,13 @@ distclean: clean
 
 TMP=$(PWD)/tmp
 MODVERDIR=$(TMP)/.tmp_versions
+
+#The actual compilation targets are run on a recursive make, so
+#this setting of MAKEFLAGS will paralellize automatically.
+#For some reason -j8 is not correct in MAKEFLAGS so -j 8 is needed
+ifeq ($(MAKEFLAGS),)
+MAKEFLAGS='-j 8'
+endif
 
 modules:
 	mkdir -p $(MODVERDIR)
@@ -87,7 +134,16 @@ ifeq ($(KSRC),$(KSRC_OUTPUT)) # We're not outputting elsewhere
 ifdef ($(KSRC)/.tmp_versions)
 	-cp $(KSRC)/.tmp_versions/*.mod $(MODVERDIR)
 endif
-	$(MAKE) -C $(KSRC) M=$(PWD) MODVERDIR=$(MODVERDIR) modules
+	$(MAKE) -C $(KSRC) M=$(PWD) MODVERDIR=$(MODVERDIR) modules \
+	|& tee $(TMP)/make.out
+	@if grep -i "WARN" $(TMP)/make.out > /dev/null; \
+	then echo "There were warnings. Aborting."; \
+        exit 1; \
+	fi
+	@if grep -i "ERROR" $(TMP)/make.out > /dev/null; \
+	then echo "There were errors. Aborting."; \
+        exit 1; \
+	fi
 else # We've got a kernel with seperate output, copy the config, and use O=
 	mkdir -p $(TMP)
 	cp $(KSRC_OUTPUT)/.config $(TMP)
@@ -97,24 +153,25 @@ endif
 install: modules
 	sudo install -d $(KMISC)
 	sudo install -m 644 -c $(addsuffix .ko,$(list-m)) $(KMISC)
-	sudo cp sivfs.h /usr/local/include
-	sudo /sbin/depmod -a ${KVER}
-	sudo rmmod $(addsuffix .ko,$(list-m)) || true
+	sudo mkdir -p /usr/local/include/sivfs
+	sudo cp *.h /usr/local/include/sivfs
+#        sudo /sbin/depmod -a ${KVER}
+#	( sudo rmmod $(addsuffix .ko,$(list-m)) >& /dev/null ) || true
 	sudo insmod $(addsuffix .ko,$(list-m))
 	sleep 1
 	sudo chmod ugo+rw /dev/sivfs
 
 uninstall:
-	rm -rf $(addprefix $(KMISC),$(addsuffix .ko,$(list-m)))
-	/sbin/depmod -a ${KVER}
-
-
-.PHONY: TAGS tags check_inc
+	sudo rm -rf $(addprefix $(KMISC),$(addsuffix .ko,$(list-m)))
+	sudo /sbin/depmod -a ${KVER}
+	sudo rm -rf /usr/local/include/sivfs
 
 RCS_FIND_IGNORE := \( -name SCCS -o -name BitKeeper -o -name .svn -o -name CVS \) -prune -o
 define all-sources
 	( find . $(RCS_FIND_IGNORE) -name '*.[chS]' -print )
 endef
+
+.PHONY: TAGS tags check_inc
 
 TAGS:
 	$(all-sources) | etags -
@@ -122,4 +179,3 @@ tags:
 	rm -f $@
 	CTAGSF=`ctags --version | grep -i exuberant >/dev/null && echo "-I __initdata,__exitdata,EXPORT_SYMBOL,EXPORT_SYMBOL_NOVERS"`; \
 	$(all-sources) | xargs ctags $$CTAGSF -a
-
